# Generated by Django 6.1.1 on 2026-09-29 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.saleitem')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocklot')),
            ],
        ),
    ]
