# Generated by Django 6.1.1 on 2026-10-06 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_saleallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.customer'),
        ),
        migrations.AlterField(
            model_name='saleallocation',
            name='stock_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stocklot'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product'),
        ),
    ]
