# Generated by Django 6.1.1 on 2026-10-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LOYER', 'Loyer'), ('ELECTRICITE', 'Électricité'), ('EAU', 'Eau'), ('TRANSPORT', 'Transport'), ('SALAIRE', 'Salaire'), ('TELEPHONE', 'Téléphone / Internet'), ('ENTRETIEN', 'Entretien'), ('FOURNITURES', 'Fournitures'), ('AUTRE', 'Autre')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
